use crate::cpu::Cpu;
use crate::get_u16register;
use crate::mmu::Mmu;

impl Cpu {
    // TODO: implementare i prefixed CB seguendo il file opcode.json.
    // Ogni funzione qui sotto deve eseguire l'istruzione corrispondente e aggiornare pc/cycles/flag come richiesto.
    pub fn cb_0x00(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x01(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x02(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x03(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x04(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x05(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x06(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x07(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x08(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x09(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x0f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x10(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x11(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x12(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x13(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x14(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x15(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x16(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x17(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x18(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x19(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x1f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x20(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x21(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x22(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x23(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x24(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x25(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x26(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x27(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x28(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x29(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x2f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x30(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x31(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x32(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x33(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x34(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x35(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x36(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x37(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x38(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x39(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x3f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x40(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x41(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x42(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x43(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x44(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x45(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x46(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x47(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x48(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x49(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x4f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x50(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x51(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x52(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x53(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x54(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x55(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x56(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x57(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x58(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x59(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x5f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x60(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x61(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x62(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x63(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x64(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x65(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x66(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x67(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x68(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x69(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x6f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x70(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x71(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x72(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x73(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x74(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x75(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x76(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x77(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x78(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x79(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x7f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x80(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x81(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x82(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x83(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x84(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x85(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x86(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x87(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x88(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x89(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x8f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x90(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x91(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x92(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x93(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x94(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x95(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x96(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x97(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x98(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x99(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9a(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9b(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9c(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9d(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9e(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0x9f(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xa9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xaa(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xab(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xac(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xad(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xae(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xaf(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xb9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xba(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xbb(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xbc(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xbd(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xbe(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xbf(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xc9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xca(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xcb(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xcc(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xcd(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xce(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xcf(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xd9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xda(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xdb(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xdc(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xdd(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xde(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xdf(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xe9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xea(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xeb(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xec(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xed(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xee(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xef(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf0(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf1(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf2(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf3(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf4(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf5(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf6(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf7(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf8(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xf9(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xfa(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xfb(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xfc(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xfd(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xfe(&mut self, _mmu: &mut Mmu) {}
    pub fn cb_0xff(&mut self, _mmu: &mut Mmu) {}
}
